#!/usr/bin/env bash
# Regenerate docs/evidence/admission-enforcement.md from a live cluster.
#
# ADR-007 says evidence is generated, never transcribed. The CI half honours
# that by capturing the verify job's stdout. This half cannot: there is no
# cluster in CI. So the equivalent guarantee is this script — it runs
# scripts/demo.sh against the real cluster and pastes the real output, which
# means the evidence file and the recorded demo are the same run of the same
# script and cannot drift apart.
#
#   KUBECTL="sudo kubectl --kubeconfig=/etc/kubernetes/admin.conf" \
#     ./scripts/collect-admission-evidence.sh > docs/evidence/admission-enforcement.md
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KUBECTL="${KUBECTL:-kubectl}"

kver=$($KUBECTL -n kyverno get deploy kyverno-admission-controller \
        -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null)
node=$($KUBECTL get nodes -o jsonpath='{.items[0].status.nodeInfo.kubeletVersion}' 2>/dev/null)

cat <<HEADER
# Evidence — admission enforcement

**Generated by \`scripts/collect-admission-evidence.sh\`. Do not edit by hand.**

Captured: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
Cluster:  kate-node-01, kubernetes $node
Kyverno:  $kver

This is the other half of [supply-chain-verification.md](supply-chain-verification.md).
That file proves the pipeline produced a signed, attested artifact. This one
proves a cluster refuses everything else.

Everything below is the verbatim stdout of \`scripts/demo.sh\`, which is the same
script recorded in [docs/img/demo.gif](../img/demo.gif).

## What each case is testing

| # | Image | Why it is here | Expected |
|---|-------|----------------|----------|
| 1 | our image, by digest | the happy path must still work, or the policy is just a brick | admit |
| 2 | \`busybox\`, by digest | an ordinary unsigned image | deny |
| 3 | \`kyverno\`, by digest | really signed, really in Rekor, wrong identity — separates "has a signature" from "has our signature" | deny |
| 4 | our image, by tag | the signature covers a digest; a tag is a mutable pointer to one | deny |

## Captured run

\`\`\`console
HEADER

KUBECTL="$KUBECTL" "$HERE/demo.sh" 2>&1

cat <<'FOOTER'
```

## What this does and does not prove

- **Does** prove the cluster denies an unsigned image, denies an image signed by
  a different keyless identity, and denies a mutable tag — in `Enforce`, with
  `failurePolicy: Fail`, with nothing switched off to make it pass.
- **Does** prove both halves of the identity pin are load-bearing. Corrupting
  the subject or the issuer alone turns case 1 from admitted into denied; that
  was run separately and is recorded in `docs/PROGRESS.md` step 2.
- **Does not** prove the source was benign. Provenance says where an artifact
  came from, never that what came from there was safe. Threat model T3.
- **Does not** cover every namespace. Rule 2 is opt-in by namespace label, and
  `kube-system`, `kyverno`, `calico-system` and `tigera-operator` are excluded
  from rule 1. Both are enumerated and argued in `policies/kyverno/verify-images.yaml`.
- **Note on the last command:** `cosign verify-attestation` returns *two* SLSA
  provenance documents, one written by `cosign attest` and one by
  `actions/attest-build-provenance`. Kyverno can only discover the second of
  them on GHCR. That asymmetry is the subject of ADR-009 and is visible in the
  output above rather than hidden.
FOOTER
