#!/usr/bin/env bash
# Regenerate docs/evidence/supply-chain-verification.md from a live registry.
#
# Everything in that file is captured output, not prose about what the output
# would look like. If this script cannot run, the evidence file does not get
# updated — a stale claim is worse than an absent one.
set -euo pipefail

IMAGE="${IMAGE:-ghcr.io/pontope/provenancepipeline}"
TAG="${TAG:-latest}"
IDENTITY="${IDENTITY:-https://github.com/PontoPe/ProvenancePipeline/.github/workflows/release.yml@refs/heads/main}"
ISSUER="${ISSUER:-https://token.actions.githubusercontent.com}"
OUT="${OUT:-docs/evidence/supply-chain-verification.md}"

DIGEST="${DIGEST:-$(docker buildx imagetools inspect "${IMAGE}:${TAG}" --format '{{.Manifest.Digest}}')}"
REF="${IMAGE}@${DIGEST}"

run() {
  echo "\$ $*"
  # Verification failures must be visible in the evidence, not swallowed.
  "$@" 2>&1 || echo "[command exited non-zero: $?]"
}

{
  echo "# Supply-chain verification — captured output"
  echo
  echo "Generated by \`scripts/collect-evidence.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo "- image: \`${REF}\`"
  echo "- certificate identity: \`${IDENTITY}\`"
  echo "- certificate OIDC issuer: \`${ISSUER}\`"
  echo
  echo '```console'
  run cosign verify --certificate-identity "$IDENTITY" --certificate-oidc-issuer "$ISSUER" "$REF"
  echo
  run cosign verify-attestation --type spdxjson --certificate-identity "$IDENTITY" --certificate-oidc-issuer "$ISSUER" "$REF"
  echo
  run cosign verify-attestation --type slsaprovenance1 --certificate-identity "$IDENTITY" --certificate-oidc-issuer "$ISSUER" "$REF"
  echo '```'
} > "$OUT"

echo "wrote $OUT"
